name: Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  phpunit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      - name: Start services
        run: docker compose up -d

      - name: Install PHP dependencies
        run: composer install --no-interaction --no-progress

      - name: Run migrations
        run: |
          php bin/console doctrine:database:create --env=test
          php bin/console doctrine:migrations:migrate --env=test

      - name: Install Xdebug
        run: sudo apt-get install php-xdebug

      - name: Run tests with coverage
        run: |
          export XDEBUG_MODE=coverage
          vendor/bin/phpunit --coverage-clover coverage.xml

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
